In [1]:
import numpy as np

In [2]:
L = [1, 4, 5, 7]
test_arr = np.array(L)
test_arr

array([1, 4, 5, 7])

In [3]:
test_arr[3]

7

In [4]:
test_arr[2]

5

In [5]:
test_arr[:2]

array([1, 4])

In [6]:
test_arr[2:]

array([5, 7])

In [7]:
test_arr.shape

(4,)

In [8]:
L = [2, 4, 5.1, 3.14]
np.array(L)

array([2.  , 4.  , 5.1 , 3.14])

In [10]:
L = [[1,2,3,4,5], [6,7,8,9,10]]

np.array(L)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
np.array(L).shape

(2, 5)

In [13]:
L = [[1,2,3,4,5], [6,7,8,9,10]]
li = np.array(L)
li

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
li.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [16]:
li.reshape(10)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
li.reshape(2,5,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [19]:
Li = li.reshape(2,5)
Li


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
Li[1]

array([ 6,  7,  8,  9, 10])

In [22]:
Li[1, 3]

9

In [23]:
Li[0, 4]

5

In [26]:
Li[0, 0] = 100
Li

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [27]:
tm = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
tm

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
tm[1, 2]

8

In [30]:
tm[:, 1]

array([2, 7])

In [33]:
tm[:, 3:]

array([[ 4,  5],
       [ 9, 10]])

In [34]:
tm[:, 1:3]

array([[2, 3],
       [7, 8]])

In [35]:
tm[:, 1:4:2]

array([[2, 4],
       [7, 9]])

In [38]:
list(np.arange(1, 11, 0.3))

[1.0,
 1.3,
 1.6,
 1.9000000000000001,
 2.2,
 2.5,
 2.8000000000000003,
 3.1000000000000005,
 3.4000000000000004,
 3.7,
 4.0,
 4.300000000000001,
 4.6000000000000005,
 4.9,
 5.200000000000001,
 5.500000000000001,
 5.800000000000001,
 6.1000000000000005,
 6.4,
 6.700000000000001,
 7.000000000000001,
 7.300000000000001,
 7.600000000000001,
 7.900000000000001,
 8.200000000000001,
 8.5,
 8.8,
 9.100000000000001,
 9.400000000000002,
 9.700000000000001,
 10.000000000000002,
 10.3,
 10.600000000000001,
 10.900000000000002]

In [40]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
tm = np.arange(1, 31).reshape(5,6)
tm

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [46]:
tm.sum()

465

In [47]:
tm.max()

30

In [49]:
tm.mean()

15.5

In [50]:
tm.sum(axis = 0)

array([65, 70, 75, 80, 85, 90])

In [51]:
tm.sum(axis = 1)

array([ 21,  57,  93, 129, 165])

In [52]:
tm.max(axis = 1)

array([ 6, 12, 18, 24, 30])

In [60]:
yb = np.arange(6).reshape(2, 3)
ob = np.arange(6).reshape(2, 3)

In [61]:
ob

array([[0, 1, 2],
       [3, 4, 5]])

In [62]:
yb + ob

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [63]:
yb

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
yb + 2

array([[2, 3, 4],
       [5, 6, 7]])

In [65]:
you = np.arange(21)
you

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [66]:
you[you > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [67]:
you[you % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [69]:
you[(you > 7) & (you < 18) & (you % 2 == 0)]

array([ 8, 10, 12, 14, 16])